### ISSUE TITLE
Authenticated Stored XSS on Title Input

### ISSUE THREAD

**Issue by andresesam** [marcantondahmen/automad#11]
Hello again, the current version of Automad is vulnerable to a stored xss. 
To reproduce this, go to the dashboard as an authenticated user and change the title of a page as shown in the screenshot. 

An attacker may be able to gain access to sensitive information such as cookies.

![automad_stored_xss](https://user-images.githubusercontent.com/39090774/84675823-13df1e80-af2d-11ea-8115-2921e564c0b5.png)

![stored_poc_automad](https://user-images.githubusercontent.com/39090774/84675831-15a8e200-af2d-11ea-99eb-985110b2a88f.png)

**Comment by marcantondahmen** [comment]
Hi, thank you for reporting this. Always appreciated! I have been taking a look at this issue in the last two days. I definitely agree with you that it is important to prevent XSS attacks, how unlikely they may be! 🤓

The issue you point out here requires the attacker to be authenticated though in order to be able to store that manipulated title. Therefore that is not really a threat. But you're still right here, because a possible scenario could be an attack via a manipulated URL sent by email. I just released version 1.5.4 which addresses that particular problem. So, thanks for actually making me look at it. 

However, I think it should still be possible for an authenticated user to add some JS to the header or footer sections. Since such an user is able to do anything on that installation, adding JS is not an issue here. 
Please note that since the recent release, cookies are not accessible via JS anymore in order to prevent stealing user information with a possible XSS attack.
