### ISSUE TITLE
Regex image selection shouldn't fallback if explicitely set

### ISSUE THREAD

**Issue by bloomvdomino** [marcantondahmen/automad#20]
Hello there!

If you use a regex to select an image, e.g. for `imageTeaser` in the various themes, and set them to a value that doesn't match any filename, `imageTeaser` falls back to the default selection regex (the first image I guess). In the most cases that seems to be an practical feature, e.g. if someone has a typo in the regex. This way it's ensured that a teaser image is selected.

BUT: If you have one ore more images in your page that are only for illustrational purposes (e.g. a statistic) and no photos (you may want to have as teaser), and those images (the illustrational…) should therefore not display as `imageTeaser`, the most obvious way would be to set the `imageTeaser` regex to something unmatching (e.g. a dash "`-`"), so no image should be selected. However, `automad` falls back and the unwanted image is used for the preview.

I see no other way to prevent `automad` from selecting those images as default image e.g. for `imageTeaser`.

What do you think about it?

**Comment by marcantondahmen** [comment]
Hi there! 

I understand and I agree that under certain conditions that behaviour might not fit all needs. I guess you're using the _Standard_ theme. Please note that this issues is actually not really related to the CMS itself. It's just a setting for that particular theme. The problem is that it could break someone else's site in case the behaviour would change. It could be that there is a global default defined that doesn't match a page's file selection and therefore the image has to be take from the content. In that case the variable is actually defined globally but will not match anything and the teaser would end up empty. To stay backwards compatible I hope you understand that I would rather like to stick with the current settings.     

However, since it is actually theme related, you could also quickly duplicate the theme in use and change the template accordingly. I think that would be the easiest for now.

I hope that helps you a bit.
