### ISSUE TITLE
cookie?

### ISSUE THREAD

**Issue by PetersOtto** [marcantondahmen/automad#21]
Hello
I have just one short question. Is it possible to run Automad without the cookie "Automad-1d0a6ada16979d3104bf3f7787a80f24"?
Best regards,
O.

**Comment by marcantondahmen** [comment]
Hi there, unfortunately this is not possible. Is there a specific scenario where a cookie is problematic for you?

**Comment by PetersOtto** [comment]
Hi Marc

Im searching for a CMS solution that do not use cookies.

In my opinion in Germany it is not so clear how to handle the cookies regarding the DSGVO.
Cookies should be only set, when the user it allows. Only really necessary cookies can be set from the beginning. However than you have to explain what the cookie do. And I am not 100% sure if you need a cookiebar than. I do not like cookiebars.

The easiest way is to work without cookies.

Thank you for your support!

**Comment by marcantondahmen** [comment]
Hi, the cookie is required to handle sessions in order to use the dashboard. That basically applies to every CMS.   

The DSGVO actually says something slightly different and that might confuse many people. According to the DSGVO it is not allowed to store any visitor's data. That is not the case here. As you mentioned yourself, all cookies that are essential to the functionality of a site are totally allowed. 

I think it is important to understand that not all cookies serve the same purpose. They are just part of the client/server communication. The German DSGVO simply wants to protect a visitor's privacy. But that privacy is not in danger here at all. 

And therefore — and that is most important — you **don't** need to add any cookie agreement notification on your site!

**Comment by PetersOtto** [comment]
Thank you for your explanation!
