### ISSUE TITLE
 Storage XSS vulnerability in /gui/accounts.php 

### ISSUE THREAD

**Issue by Pwn2OwnEr** [marcantondahmen/automad#29]
Add a user with name："><script>alert(document.cookie)</script>。
![图片](https://user-images.githubusercontent.com/44282003/126676741-e81b95c4-97a1-49f5-bd9d-9dab5a7a98b0.png)
![图片](https://user-images.githubusercontent.com/44282003/126676931-04c9b272-49c7-4422-8696-6c8ad5b3c210.png)
xss payload was embeded in config/accounts.php： 
![图片](https://user-images.githubusercontent.com/44282003/126677172-8be8e70b-8647-4467-ab9a-e7560b2588e5.png)
/gui/accounts.php：add() function without verify the user input！
![图片](https://user-images.githubusercontent.com/44282003/126678221-6a28bf71-f175-44a0-a377-8f77481d48eb.png)

**Comment by marcantondahmen** [comment]
Hi, thanks for reporting this. However an attacker must be authenticated to use that vulnerability which somehow defeats its purpose. Stealing session IDs in that scenario would giving him the same permissions he already has to actually use that vulnerability.

Still, you are right it shouldn't be possible and therefore it is fixed in the latest release. 🙂
