### ISSUE TITLE
Remove bespoke template engine for a proper one (e.g., Twig or Smarty)

### ISSUE THREAD

**Issue by jordanbrauer** [marcantondahmen/automad#3]
Currently the template engine for this project (while cute) is _severely_ gimped. I think that it should be dropped entirely and replaced with the likes of something proven and battle hardened, like [Twig](https://github.com/twigphp/Twig) or _at least_ [Smarty](https://github.com/smarty-php/smarty).

This CMS has a huge potential, but the template engine is a huge setback. The core problems I see with it:

- syntax is extremely cumbersome (more so than any template engine I have used, at least)
- poor variable support (no arrays or objects?)
- lacking critical string and array manipulation functions
- control structures/functions/filters are poorly named

**Comment by marcantondahmen** [comment]
Hi,

I'm not exactly sure about the objective of this issue since it is very opinion-based and not really pointing out any bug, making a feature request or giving any constructive feedback that would help to improve the software. 

Regarding your "issue", please note that there is also the option to write templates in plain PHP to handle more complex projects. Or you just write a little extension since the engine itself is very extendable. Aside of that, the points you mention are not reflecting its actual set of features. I will try to comment on your list:

* A little comparison to Twig in terms of cumbersome syntax: 
  A Variable in Twig

        {{var|escape}} 

  would be in Automad

        @{var|escape} 
  
  And a loop in Twig
        
        {% for page in pages %}
            * {{ page.title }}
        {% endfor %}

   would be in Automad:
   
        <@ foreach in pagelist @>
            * @{ title }
        <@ end @>
  
  Note that you can even iterate a list of images while resizing them at the same time in one single statement (I can't find quickly any example for this task in Twig):

        <@ foreach in '*.jpg' { width: 300, height: 200, crop: true } @> 
            <img src="@{ :fileResized }">
        <@ end @> 

  I'm not sure how to do that in Smarty.
* Some kind of objects are supported, like pagelists, filters, tags and a filelist. All of those objects are configurable. Basically objects here are boiled down to the essentials for developing websites like portfolios or blogs. Generic arrays can be handled by using PHP.
* What is a critical string manipulation function?
* What do you mean with poorly named?

There is also [this article on CSS-Tricks](https://css-tricks.com/developing-with-automad/) giving a little introduction into the template language. 

I hope this can clear up some of the misunderstandings. You can find more information on writing templates in the official docs.
