### ISSUE TITLE
Be specific about the required directory and file permissions — and how to get them

### ISSUE THREAD

**Issue by michaellenaghan** [marcantondahmen/automad#53]
The docs point to [this](https://stackoverflow.com/questions/9046977/xampp-permissions-on-mac-os-x/38946143#38946143) StackOverflow answer when talking about the required directory and file permissions. Unfortunately it isn't very clear exactly which answer is being pointed to — and many of answers give terrible advice, e.g.:

    chmod -R 0777  /opt/lampp/htdocs/

My preferred host says this about those permissions:

> If you look online, you may find advice telling you to set all directories to 777 and all files to 666. This is terrible advice. Roughly translated it means "I don't understand Unix file permissions well enough to help you, but doing this will hide the problem for now, and I'll be long gone when this terrible advice I'm giving you lets hackers completely overwrite your site."

WordPress.org also has a [long aside](https://wordpress.org/support/article/changing-file-permissions/#the-dangers-of-777) about the dangers of 0777.

If you're interested, I'd like to write up — or help you write up — better instructions for the docs.

What I'd like to do is have two or three scenarios, from most permissive to least. The most permissive might show how to set permissions correctly, but more broadly than needed. The least permissive might show how to set them so that, say, you can edit files, but you can't update through the web. The middle option would perhaps only set write permissions on the directories and files that actually need it. See [this](https://docs.boltcms.io/5.0/installation/permissions) page from BoltCMS to get a sense of what I mean.

As far as updating through the web goes, I'll again point to something my preferred host says:

> We strongly discourage members from making script files and key directories (like /home/public) writeable by the web user. This setting is used by some applications to enable self-updating over the web. We discourage that practice as well; if you can update your site over the web, so can someone else, and the site may look very different when they finish with it. We recommend using out-of-band methods to update site applications.

I know that most people wouldn't go this far, but I plan to use your command-line tool to do updates. The point of that, though, would be to avoid making things writable that don't need to be writeable for typical use. I could try figuring that out by trial and error, but it would be easier with your help. That's why I'm offering to help with the writing in return. :-)

**Comment by marcantondahmen** [comment]
Hi there and thanks for the great input. However, just to clarify, the documentation doesn't say that the permission should be changed to 777. 

The only thing is that it must be possible for the server, or better for PHP, to write to files and folders. It also states that the best solution would be to use Fast-CGI or php-fpm instead of an Apache module in order to avoid permission issues. The linked StackOverflow answer only shows how to change permissions on macOS using Finder in the case that someone less experienced plays around with XAMPP or similar.

Regarding the updater I think that it is of course generally correct to limit write access. That is always true. But I guess that this is an easy statement for any host in order to avoid doing something wrong and doesn't really reflect reality in terms of application requirements. 

Packages and updates are pulled from known and defined sources. It is also important to know that it is not possible to upload PHP files from the dashboard. 

Also I think that _"if you can update your site over the web, so can someone else"_ is a bold statement. It implies that being hacked is basically just normal and happens permanently to everybody everywhere. Yes, someone can do harm to a website when breaking in. That applies to every CMS where you can install or update things and simply can not be avoided. When you are hacked you are hacked and the hacker has then the privileges you have. And the more power you have, the more damage can be done. In such a scenario file permissions can't help you.

A good host will put your site in a sandbox and that's it. It is in the end about the balance between risk and convenience. 

However, there are things that can be done in order to significantly improve security:

1. Change the URL for the dashboard to something custom that is less likely to be attacked.
2. Or, disable the dashboard entirely by setting `AM_PAGE_DASHBOARD` to `false` and only active it when needed.
3. Or, disable the dashboard and have a local working copy that is synced to the web server using `rsync` or similar.

That all being said, it would be more than appreciated to have detailed or easier to understand instructions on how to set permissions on different systems. It would be great to create a new thread for that in the forum that can be checked out when people are struggling. 

Looking forward to read it! Thanks!

**Comment by michaellenaghan** [comment]
If we follow up on the topic of security, I will nudge you to think differently. :-) 

I've now put Automad into production, so I can dig into some details on the more specific topic I opened this issue with.

Here's a quick, off-the-cuff take on what I had in mind.

===

Sometimes when you run Automad in a development setting, you run under your own credentials. When you run Automad in production, you never do.

If Automad was a static site generator that difference wouldn't really matter. But Automad isn't a static site generator, it's an app that allows you to make changes to your site over the web. That means that the user account the web server runs under — that Automad runs under — has to be able to change your site. Your files.

At one extreme, you could simply hand all of your files over to the web server. At the other, you could give the web server only the permissions it needs to do exactly what you want it to do, and no more. 

If you take the first option you might discover, for example, that the web server is creating files you can't delete. If you take the second, you might discover that some things in Automad — like self-updates — don't work.

Hopelessly tangled with the question of functionality is the question of security. Under the first option, for example, you've increased your vulnerability compared to the second. Automad can do more — but so anyone who successfully hacks Automad.

Unfortunately, there's no right answer here, just a series of trade-offs. Some people lock their front doors even when they're home. Some people don't. It's a bit like that.

Here's a description of how to set up Automad that tries to help you make the right choice. For you.

The options that follow focus on the big picture. I'll get into the technical details below. For now, I'm just going to assume two little helpers that fix up directories (`automad_fix_dirs.sh`) and files (`automad_fix_files.sh`).

1. This is the easiest option, but it opens up more than it really needs to open up.

        automad_fix_dirs.sh automad

2. This is a little more work, but more specific. Functionally, it's about the same.

        automad_fix_dirs.sh automad/{automad,cache,config,lib,packages,pages,shared}
        automad_fix_files.sh automad/{index.php,sitemap.php}

3. This preserves the ability to update the site over the web, but loses the ability to install packages or update Automad itself. (You'd install packages and update Automad from the command-line.)

        automad_fix_dirs.sh automad/{cache,config,pages,shared}
        automad_fix_files.sh automad/{sitemap.php}

4. This preserves the ability to run the site over the web, but loses the ability to do everything else. (You'd run Automad elsewhere and sync the changed files to your web host.)

        automad_fix_dirs.sh automad/{cache}
        automad_fix_files.sh automad/{sitemap.php}

If the technical details aren't interesting you can stop here and choose!

===

At this point I was thinking that it would be good to get into some of the technical details, and the technical tradeoffs. I won't do that now, but but I can show you the helpers.

`automad_fix_dirs.sh`:

```
#!/bin/env bash

set -eu

for DIR in "$@"
do
    mkdir -p $DIR
    find $DIR -type d -user $(id -u) ! -perm -g+ws -exec chmod g+ws \{} +
    find $DIR -user $(id -u) ! -perm -o+w  -exec chmod o+w  \{} +
done
```

`automad_fix_files.sh`:

```
#!/bin/env bash

set -eu

for FILE in "$@"
do
    touch $FILE
    chmod o+w $FILE
done
```

I think there are two main approaches to giving the web server access. I tried both, and settled on this one. ("Both" here refers to the approaches, not the helpers. Both approaches use two helpers.)

I should note that I don't know if all of the details are correct. For example, option 4 says that you just need to touch one dir and one file for running-without-editing, but I didn't test that; that's the kind of thing I thought you could help with, by letting me know how things actually work.

I should also note that there's a problem I ran into and had to work around. I'll open a separate issue for that.

**Comment by michaellenaghan** [comment]
I think this isn't of interest, so I'll close it. Here's a different, quick-fix suggestion: find a page with a good explanation, and link to that instead of a Stack Overflow answer.
