### ISSUE TITLE
Content isn't being properly HTML/JS/XML encoded, pt. 2

### ISSUE THREAD

**Issue by michaellenaghan** [marcantondahmen/automad#59]
>> I was able to demonstrate that I could execute files you didn't think would be executed through the browser.
>
> Where did you exactly demonstrate that? And which files are you talking about? This is a very bold claim you make here.
>
> Just to be clear here in case other users come across here, accessing PHP source files is not possible, accessing tests gives you just a blank page for obvious reasons, accessing Javascript source files or templates is irrelevant.
>
> What you state is simply not true.

Good heavens. 

[Here](https://dev.automad.org/lib/vendor/michelf/php-markdown/Readme.php) is further proof. Click the link and you'll see the contents of `lib/vendor/michelf/php-markdown/Readme.php`, a PHP file, on your demo site. 

You'll see the contents because the PHP file was *executed*.

And not by Automad. 

(The contents aren't *in* that file, they're *read* by that file.)

It just takes a simple `grep` to find all of the PHP files that don't immediately die. 

There are ~150 of them.

I get the message, though. I'll stop posting bugs.

P.S. The bug you closed and locked wasn't about executable content, it was about a failure to properly escape content. That's a major bug, and it's certainly not resolved.

**Comment by marcantondahmen** [comment]
Wow, you really made it work to show a readme file. What do you actually want to do here aside from ranting? I don't see how your way of posting issues is helping anyone. Your proof is just irrelevant.

The original issue was valid and nobody doubts that. But you instead of just leaving it and wait until it gets fixed you started a rant and that is not compatible with a culture of communication I would like to see in a project like this where a good spirit is the main driver.
