### ISSUE TITLE
Localized date

### ISSUE THREAD

**Issue by bricebou** [marcantondahmen/automad#84]
Hey,

I'm pursuing my usage of Automad and I am wondering if there is a way to localize date using the default theme ?

I've configured the locale to 'fr_FR' and the date format to 'j F Y' for posts and projects but the month still is in english.

Thanks again !

**Comment by marcantondahmen** [comment]
Hi there, in order to localize dates you have to use the ICU syntax for the date field, add the correct value for the locale field and make sure the locale is installed on your server.

You can find more information about date formatting in the docs for the [dateFormat](https://automad.org/developer-guide/building-themes/template-language/pipe/dateformat) function that is used in templates to handle dates.

**Comment by bricebou** [comment]
Thanks a lot ! I've changed the syntax I used and I had to load manually the intl PHP module on my shared hosting...

Thanks again, thanks a lot for this really nice Automad !
