### ISSUE TITLE
Pagelist: display only future events

### ISSUE THREAD

**Issue by Pentaonia** [marcantondahmen/automad#86]
Hi,
I'm using the pagelist widget. Everything is working fine, thank you for your great work(!), but I have a question:

![image](https://github.com/marcantondahmen/automad/assets/93387223/38db4893-d17f-4f6e-9d7f-7557be7e5ba7)

What do I have to do to show only pages with a date in the future?

Best
Loubert

**Comment by marcantondahmen** [comment]
Hi there, the default pagelist block template doesn't support filtering by date. However, you can write a new template for the pagelist block or modify the one you are using in order to add a conditional that compares the page date with the current datetime. The current datetime can be accessed using the `@{ :now }` runtime variable. The conditional would look as follows:

```php
<@ if @{date} >= @{:now} @>
    @{title}
<@ end @>
```

You can find more info in the docs about how to use templates for blocks.

**Comment by Pentaonia** [comment]
Hey Marc,

works perfectly! Just copied a template in `/packages/standard/templates/blocks/pagelist` and wrapped all after the `foreach` in your conditional.
